name: Maven Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

#       - name: Build with Maven
#         run: mvn clean install

      - name: Build with Maven
        run: mvn clean verify

      - name: Generate Cucumber report
        run: mvn net.masterthought:maven-cucumber-reporting:5.6.0:generate -e
        
#       - name: Build with Cucumber report generation
#         run: mvn clean install -DskipTests=true net.masterthought:maven-cucumber-reporting:5.6.0:generate
     
        
      - name: Generate test report with Cucumber plugin
        run: mvn verify
        
      - name: List directory contents
        run: ls target/cucumber-reports/

      - name: Run tests with Surefire plugin
        run: mvn surefire:test

      

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-reports
          path: target/cucumber-reports/


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#           distribution: 'adopt'
          
# #       - name: Build with Maven
# #         run: mvn clean verify

# #       - name: Generate Cucumber report
# #         run: mvn verify net.masterthought:maven-cucumber-reporting:5.6.0:generate
        
#       - name: Build with Maven
#         run: mvn -B package --file pom.xml

#       - name: Generate Cucumber Reports
#         uses: mvnrepository/cucumber-reporting@2.8.0
#         with:
#           files: |
#             target/cucumber-reports/cucumber.json
#           outputDir: target/cucumber-html-reports

#       - name: Upload report
#         uses: actions/upload-artifact@v2
#         with:
#           name: cucumber-reports
#           path: target/site/cucumber-reports/cucumber-pretty/index.html

