name: Action Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Action
        id: hello
        uses: actions/simple-java-maven-app@v1
        with:
          say-hi-to: githubactions
          
      - name: Time now
        run: echo "{{ steps.hellp.outputs.time }}"
      
