on:
  push:

name: Java CI with Gradle



  
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Publish Test Results
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/
