name: TX_Load_Group_1010

on:
  workflow_dispatch:
  workflow_call:

jobs:
  LG_Data_Watcher_1011:
    runs-on: ubuntu-latest
    steps:
      - name: LG Data Watcher
        run: |
          echo "Hello"
        # Update with the appropriate steps for LG Data Watcher

  Pre_Load_Register_Usage_TX_1020:
    needs: LG_Data_Watcher_1011
    runs-on: ubuntu-latest
    concurrency:
      group: my-concurrency
      cancel-in-progress: false
    steps:
      - name: Configure SSH
        run: |
          echo "Hello"
      
      
      - name: Pre Load Usage TX 1015
        run: |
          echo "Hello"
        # Update with the appropriate steps for Pre Load Usage TX 1015

      - name: Pre Load Usage TX 1020C
        run: |
          echo "Hello"
        # Update with the appropriate steps for Pre Load Usage TX 1020C

  Load_Usage_TX_1020:
    needs: Pre_Load_Register_Usage_TX_1020
    runs-on: ubuntu-latest
    concurrency:
      group: my-concurrency
      cancel-in-progress: false
    steps:
      - name: Configure SSH
        run: |
          echo "Hello"
                
      - name: Load Usage TX 1020A
        run: |
          echo "Hello"

      - name: Load Usage TX 1020B
        run: |
          echo "Hello"

  Load_Monitor_TX_1021:
    needs: Load_Usage_TX_1020
    runs-on: ubuntu-latest
    concurrency:
      group: my-concurrency
      cancel-in-progress: false
    steps:
      - name: Configure SSH
        run: |
          echo "Hello"
      
      - name: Load Monitor TX
        run: |
          echo "Hello"
