name: TX_Load_Group_1010

on:
  workflow_dispatch:
  workflow_call:

jobs:
  LG_Data_Watcher_1011:
    runs-on: ubuntu-latest
    steps:
      - name: Data Watcher Step
        run: echo "Running Data Watcher Step"

  Pre_Load_Usage_TX_1015:
    runs-on: ubuntu-latest
    needs: LG_Data_Watcher_1011
    steps:
      - name: Pre_Load_Usage_TX_1015 Step
        run: echo "Running Pre_Load_Usage_TX_1015 Step"

  Pre_Load_Usage_TX_1020C:
    runs-on: ubuntu-latest
    needs: LG_Data_Watcher_1011
    steps:
      - name: Pre_Load_Usage_TX_1020C Step
        run: echo "Running Pre_Load_Usage_TX_1020C Step"

  Load_Usage_TX_1020A:
    runs-on: ubuntu-latest
    needs: [Pre_Load_Usage_TX_1015, Pre_Load_Usage_TX_1020C]
    steps:
      - name: Load_Usage_TX_1020A Step
        run: echo "Running Load_Usage_TX_1020A Step"

  Load_Usage_TX_1020B:
    runs-on: ubuntu-latest
    needs: [Pre_Load_Usage_TX_1015, Pre_Load_Usage_TX_1020C]
    steps:
      - name: Load_Usage_TX_1020B Step
        run: echo "Running Load_Usage_TX_1020B Step"

  Load_Monitor_TX_1021:
    runs-on: ubuntu-latest
    needs: [Load_Usage_TX_1020A, Load_Usage_TX_1020B]
    steps:
      - name: Load_Monitor_TX_1021 Step
        run: echo "Running Load_Monitor_TX_1021 Step"
