name: example-workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  sample:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        max_parallel: [1]
    steps:
      - run: sleep 30
      - run: echo "Sample job 2"
      - run: echo "Sample job 3"
  
  prebuild:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        max_parallel: [1]
    steps:
      - run: sleep 30
      - run: echo "Prebuild job 2"
      - run: echo "Prebuild job 3"

  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        max_parallel: [1]
    steps:
      - run: sleep 30
      - run: echo "Build job 2"
      - run: echo "Build job 3"
