name: example-workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sample:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "Hello, world!"

  prebuild:
    runs-on: [ubuntu-latest]
    concurrency:
      group: my-concurrency
      max: 2
    steps:
      - run: |
          echo "This is the PreBuild job."
          sleep 5
          echo "PreBuild job complete."

  build:
    runs-on: [ubuntu-latest]
    concurrency:
      group: my-concurrency
      max: 2
    steps:
      - run: |
          echo "This is the Build job."
          sleep 5
          echo "Build job complete."

  postbuild:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "This is the PostBuild job."
