name: Workflow B

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Workflow C]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow B
        run: echo "Workflow B completed"

      - name: Print Workflow Information
        run: echo "Triggered by ${{ github.event.workflow_run.workflow.name }} with run ID ${{ github.event.workflow_run.id }}"
