name: Workflow B

on:
  workflow_run:
    workflows: [Workflow A]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow B
        run: echo "Workflow B completed"

      - name: Print Workflow Information
        run: echo "Triggered by ${{ github.event.workflow }} with run ID ${{ github.event.run_id }}"
