name: Workflow A

on:
  workflow_dispatch:

jobs:
  Hello:
    uses: Abhishek00794/simple-java-maven-app/.github/workflows/workflow-b.yml@master  # Reference to Workflow B YAML file

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow A
        run: echo "Workflow A completed"

      - name: Print Workflow Information
        run: echo "Triggered by ${{ github.event.workflow }} with run ID ${{ github.run_id }}"
        
      
